# Generated by Django 4.2.5 on 2023-10-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="lastDateToApply",
            field=models.DateField(),
        ),
    ]
