# Generated by Django 4.2.6 on 2023-10-18 09:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issortlist",
            old_name="dataYouApply",
            new_name="dateYouApply",
        ),
    ]
